server:
  port: 8086
#Database Configuration
spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: root